# Generated by Django 5.2.5 on 2025-10-22 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0003_alter_produto_descricao_alter_produto_preco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='tag',
            field=models.ManyToManyField(related_name='produtos', to='estoque.protuto_tag'),
        ),
    ]
